root: true

extends:
  - airbnb

plugins:
  - react

settings:
  ecmascript: 6
  react:
    version: '17'

env:
  browser: true

rules:
  arrow-body-style: 0
  func-style: 0
  func-names: 0
  newline-per-chained-call: 0
  padding-line-between-statements: [
      "error",
      { blankLine: "always", prev: ["singleline-const", "let", "var"], next: "*"},
      { blankLine: "any", prev: ["singleline-const", "let", "var"], next: ["const", "let", "var"]},
      { blankLine: "always", prev: ["cjs-import"], next: "*"},
      { blankLine: "never", prev: ["cjs-import"], next: ["cjs-import"]},
      { blankLine: "always", prev: "*", next: "return" }
  ]
  no-console: 0
  no-plusplus: 0
  no-underscore-dangle: 0
  no-debugger: 0
  no-multiple-empty-lines: [2, { "max": 1 }]
  linebreak-style: 0
  object-curly-newline: 0
  max-len: ["error", { "code": 700, "ignoreComments": true }]
  curly: 0
  space-return-throw-case: 0
  complexity: 0
  strict: [2, "never"]
  no-confusing-arrow: 0
  no-alert: 0
  import/no-extraneous-dependencies: 0
  import/extensions: 0
  import/prefer-default-export: 0
  import/no-named-as-default: 0
  import/no-commonjs: 2
  import/no-absolute-path: 0
  react/no-string-refs: 0
  react/prop-types: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/prefer-stateless-function: 0
  react/destructuring-assignment: 0
  react/jsx-fragments: 0
  react/jsx-closing-bracket-location: [2, "after-props"]
  react/jsx-curly-newline: 0
  react/state-in-constructor: 0
  react/static-property-placement: 0
  jsx-a11y/href-no-hash: 0
  jsx-a11y/no-autofocus: 0
  jsx-a11y/alt-text: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
  react/jsx-one-expression-per-line: 0
  react/function-component-definition: 0
  react/react-in-jsx-scope: 0
  
  no-return-assign: [2, "except-parens"]
