export default [
  {
    login: 'motastan95',
    id: 12864799,
    node_id: 'MDQ6VXNlcjEyODY0Nzk5',
    avatar_url: 'https://avatars.githubusercontent.com/u/12864799?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/motastan95',
    html_url: 'https://github.com/motastan95',
    followers_url: 'https://api.github.com/users/motastan95/followers',
    following_url:
      'https://api.github.com/users/motastan95/following{/other_user}',
    gists_url: 'https://api.github.com/users/motastan95/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/motastan95/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/motastan95/subscriptions',
    organizations_url: 'https://api.github.com/users/motastan95/orgs',
    repos_url: 'https://api.github.com/users/motastan95/repos',
    events_url: 'https://api.github.com/users/motastan95/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/motastan95/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sahinyanlik',
    id: 975479,
    node_id: 'MDQ6VXNlcjk3NTQ3OQ==',
    avatar_url: 'https://avatars.githubusercontent.com/u/975479?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sahinyanlik',
    html_url: 'https://github.com/sahinyanlik',
    followers_url: 'https://api.github.com/users/sahinyanlik/followers',
    following_url:
      'https://api.github.com/users/sahinyanlik/following{/other_user}',
    gists_url: 'https://api.github.com/users/sahinyanlik/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/sahinyanlik/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sahinyanlik/subscriptions',
    organizations_url: 'https://api.github.com/users/sahinyanlik/orgs',
    repos_url: 'https://api.github.com/users/sahinyanlik/repos',
    events_url: 'https://api.github.com/users/sahinyanlik/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sahinyanlik/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'SevdaCimen',
    id: 26030084,
    node_id: 'MDQ6VXNlcjI2MDMwMDg0',
    avatar_url: 'https://avatars.githubusercontent.com/u/26030084?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/SevdaCimen',
    html_url: 'https://github.com/SevdaCimen',
    followers_url: 'https://api.github.com/users/SevdaCimen/followers',
    following_url:
      'https://api.github.com/users/SevdaCimen/following{/other_user}',
    gists_url: 'https://api.github.com/users/SevdaCimen/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/SevdaCimen/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/SevdaCimen/subscriptions',
    organizations_url: 'https://api.github.com/users/SevdaCimen/orgs',
    repos_url: 'https://api.github.com/users/SevdaCimen/repos',
    events_url: 'https://api.github.com/users/SevdaCimen/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/SevdaCimen/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mtnovl',
    id: 30976108,
    node_id: 'MDQ6VXNlcjMwOTc2MTA4',
    avatar_url: 'https://avatars.githubusercontent.com/u/30976108?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mtnovl',
    html_url: 'https://github.com/mtnovl',
    followers_url: 'https://api.github.com/users/mtnovl/followers',
    following_url: 'https://api.github.com/users/mtnovl/following{/other_user}',
    gists_url: 'https://api.github.com/users/mtnovl/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mtnovl/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mtnovl/subscriptions',
    organizations_url: 'https://api.github.com/users/mtnovl/orgs',
    repos_url: 'https://api.github.com/users/mtnovl/repos',
    events_url: 'https://api.github.com/users/mtnovl/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mtnovl/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'imposs86',
    id: 40609783,
    node_id: 'MDQ6VXNlcjQwNjA5Nzgz',
    avatar_url: 'https://avatars.githubusercontent.com/u/40609783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/imposs86',
    html_url: 'https://github.com/imposs86',
    followers_url: 'https://api.github.com/users/imposs86/followers',
    following_url:
      'https://api.github.com/users/imposs86/following{/other_user}',
    gists_url: 'https://api.github.com/users/imposs86/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/imposs86/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/imposs86/subscriptions',
    organizations_url: 'https://api.github.com/users/imposs86/orgs',
    repos_url: 'https://api.github.com/users/imposs86/repos',
    events_url: 'https://api.github.com/users/imposs86/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/imposs86/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'MrDumlu',
    id: 47226050,
    node_id: 'MDQ6VXNlcjQ3MjI2MDUw',
    avatar_url: 'https://avatars.githubusercontent.com/u/47226050?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MrDumlu',
    html_url: 'https://github.com/MrDumlu',
    followers_url: 'https://api.github.com/users/MrDumlu/followers',
    following_url:
      'https://api.github.com/users/MrDumlu/following{/other_user}',
    gists_url: 'https://api.github.com/users/MrDumlu/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/MrDumlu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/MrDumlu/subscriptions',
    organizations_url: 'https://api.github.com/users/MrDumlu/orgs',
    repos_url: 'https://api.github.com/users/MrDumlu/repos',
    events_url: 'https://api.github.com/users/MrDumlu/events{/privacy}',
    received_events_url: 'https://api.github.com/users/MrDumlu/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mkbiltek2019',
    id: 44512017,
    node_id: 'MDQ6VXNlcjQ0NTEyMDE3',
    avatar_url: 'https://avatars.githubusercontent.com/u/44512017?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mkbiltek2019',
    html_url: 'https://github.com/mkbiltek2019',
    followers_url: 'https://api.github.com/users/mkbiltek2019/followers',
    following_url:
      'https://api.github.com/users/mkbiltek2019/following{/other_user}',
    gists_url: 'https://api.github.com/users/mkbiltek2019/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mkbiltek2019/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/mkbiltek2019/subscriptions',
    organizations_url: 'https://api.github.com/users/mkbiltek2019/orgs',
    repos_url: 'https://api.github.com/users/mkbiltek2019/repos',
    events_url: 'https://api.github.com/users/mkbiltek2019/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mkbiltek2019/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'furkandelibas',
    id: 52637234,
    node_id: 'MDQ6VXNlcjUyNjM3MjM0',
    avatar_url: 'https://avatars.githubusercontent.com/u/52637234?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/furkandelibas',
    html_url: 'https://github.com/furkandelibas',
    followers_url: 'https://api.github.com/users/furkandelibas/followers',
    following_url:
      'https://api.github.com/users/furkandelibas/following{/other_user}',
    gists_url: 'https://api.github.com/users/furkandelibas/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/furkandelibas/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/furkandelibas/subscriptions',
    organizations_url: 'https://api.github.com/users/furkandelibas/orgs',
    repos_url: 'https://api.github.com/users/furkandelibas/repos',
    events_url: 'https://api.github.com/users/furkandelibas/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/furkandelibas/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'antogian',
    id: 15280729,
    node_id: 'MDQ6VXNlcjE1MjgwNzI5',
    avatar_url: 'https://avatars.githubusercontent.com/u/15280729?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/antogian',
    html_url: 'https://github.com/antogian',
    followers_url: 'https://api.github.com/users/antogian/followers',
    following_url:
      'https://api.github.com/users/antogian/following{/other_user}',
    gists_url: 'https://api.github.com/users/antogian/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/antogian/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/antogian/subscriptions',
    organizations_url: 'https://api.github.com/users/antogian/orgs',
    repos_url: 'https://api.github.com/users/antogian/repos',
    events_url: 'https://api.github.com/users/antogian/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/antogian/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'OgulcanBulut',
    id: 65467015,
    node_id: 'MDQ6VXNlcjY1NDY3MDE1',
    avatar_url: 'https://avatars.githubusercontent.com/u/65467015?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/OgulcanBulut',
    html_url: 'https://github.com/OgulcanBulut',
    followers_url: 'https://api.github.com/users/OgulcanBulut/followers',
    following_url:
      'https://api.github.com/users/OgulcanBulut/following{/other_user}',
    gists_url: 'https://api.github.com/users/OgulcanBulut/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/OgulcanBulut/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/OgulcanBulut/subscriptions',
    organizations_url: 'https://api.github.com/users/OgulcanBulut/orgs',
    repos_url: 'https://api.github.com/users/OgulcanBulut/repos',
    events_url: 'https://api.github.com/users/OgulcanBulut/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/OgulcanBulut/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mithatogulcan24',
    id: 68347457,
    node_id: 'MDQ6VXNlcjY4MzQ3NDU3',
    avatar_url: 'https://avatars.githubusercontent.com/u/68347457?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mithatogulcan24',
    html_url: 'https://github.com/mithatogulcan24',
    followers_url: 'https://api.github.com/users/mithatogulcan24/followers',
    following_url:
      'https://api.github.com/users/mithatogulcan24/following{/other_user}',
    gists_url: 'https://api.github.com/users/mithatogulcan24/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mithatogulcan24/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/mithatogulcan24/subscriptions',
    organizations_url: 'https://api.github.com/users/mithatogulcan24/orgs',
    repos_url: 'https://api.github.com/users/mithatogulcan24/repos',
    events_url: 'https://api.github.com/users/mithatogulcan24/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mithatogulcan24/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'pasalog',
    id: 11725001,
    node_id: 'MDQ6VXNlcjExNzI1MDAx',
    avatar_url: 'https://avatars.githubusercontent.com/u/11725001?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/pasalog',
    html_url: 'https://github.com/pasalog',
    followers_url: 'https://api.github.com/users/pasalog/followers',
    following_url:
      'https://api.github.com/users/pasalog/following{/other_user}',
    gists_url: 'https://api.github.com/users/pasalog/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/pasalog/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/pasalog/subscriptions',
    organizations_url: 'https://api.github.com/users/pasalog/orgs',
    repos_url: 'https://api.github.com/users/pasalog/repos',
    events_url: 'https://api.github.com/users/pasalog/events{/privacy}',
    received_events_url: 'https://api.github.com/users/pasalog/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'commodus',
    id: 1306778,
    node_id: 'MDQ6VXNlcjEzMDY3Nzg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1306778?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/commodus',
    html_url: 'https://github.com/commodus',
    followers_url: 'https://api.github.com/users/commodus/followers',
    following_url:
      'https://api.github.com/users/commodus/following{/other_user}',
    gists_url: 'https://api.github.com/users/commodus/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/commodus/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/commodus/subscriptions',
    organizations_url: 'https://api.github.com/users/commodus/orgs',
    repos_url: 'https://api.github.com/users/commodus/repos',
    events_url: 'https://api.github.com/users/commodus/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/commodus/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'aenesgur',
    id: 47754791,
    node_id: 'MDQ6VXNlcjQ3NzU0Nzkx',
    avatar_url: 'https://avatars.githubusercontent.com/u/47754791?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/aenesgur',
    html_url: 'https://github.com/aenesgur',
    followers_url: 'https://api.github.com/users/aenesgur/followers',
    following_url:
      'https://api.github.com/users/aenesgur/following{/other_user}',
    gists_url: 'https://api.github.com/users/aenesgur/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/aenesgur/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/aenesgur/subscriptions',
    organizations_url: 'https://api.github.com/users/aenesgur/orgs',
    repos_url: 'https://api.github.com/users/aenesgur/repos',
    events_url: 'https://api.github.com/users/aenesgur/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/aenesgur/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'hgunay',
    id: 19264860,
    node_id: 'MDQ6VXNlcjE5MjY0ODYw',
    avatar_url: 'https://avatars.githubusercontent.com/u/19264860?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hgunay',
    html_url: 'https://github.com/hgunay',
    followers_url: 'https://api.github.com/users/hgunay/followers',
    following_url: 'https://api.github.com/users/hgunay/following{/other_user}',
    gists_url: 'https://api.github.com/users/hgunay/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hgunay/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hgunay/subscriptions',
    organizations_url: 'https://api.github.com/users/hgunay/orgs',
    repos_url: 'https://api.github.com/users/hgunay/repos',
    events_url: 'https://api.github.com/users/hgunay/events{/privacy}',
    received_events_url: 'https://api.github.com/users/hgunay/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'lwardzala',
    id: 55432088,
    node_id: 'MDQ6VXNlcjU1NDMyMDg4',
    avatar_url: 'https://avatars.githubusercontent.com/u/55432088?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lwardzala',
    html_url: 'https://github.com/lwardzala',
    followers_url: 'https://api.github.com/users/lwardzala/followers',
    following_url:
      'https://api.github.com/users/lwardzala/following{/other_user}',
    gists_url: 'https://api.github.com/users/lwardzala/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/lwardzala/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lwardzala/subscriptions',
    organizations_url: 'https://api.github.com/users/lwardzala/orgs',
    repos_url: 'https://api.github.com/users/lwardzala/repos',
    events_url: 'https://api.github.com/users/lwardzala/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/lwardzala/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'buraksenyurt',
    id: 2705782,
    node_id: 'MDQ6VXNlcjI3MDU3ODI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2705782?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/buraksenyurt',
    html_url: 'https://github.com/buraksenyurt',
    followers_url: 'https://api.github.com/users/buraksenyurt/followers',
    following_url:
      'https://api.github.com/users/buraksenyurt/following{/other_user}',
    gists_url: 'https://api.github.com/users/buraksenyurt/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/buraksenyurt/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/buraksenyurt/subscriptions',
    organizations_url: 'https://api.github.com/users/buraksenyurt/orgs',
    repos_url: 'https://api.github.com/users/buraksenyurt/repos',
    events_url: 'https://api.github.com/users/buraksenyurt/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/buraksenyurt/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'hasancafarov',
    id: 6268797,
    node_id: 'MDQ6VXNlcjYyNjg3OTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6268797?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hasancafarov',
    html_url: 'https://github.com/hasancafarov',
    followers_url: 'https://api.github.com/users/hasancafarov/followers',
    following_url:
      'https://api.github.com/users/hasancafarov/following{/other_user}',
    gists_url: 'https://api.github.com/users/hasancafarov/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/hasancafarov/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/hasancafarov/subscriptions',
    organizations_url: 'https://api.github.com/users/hasancafarov/orgs',
    repos_url: 'https://api.github.com/users/hasancafarov/repos',
    events_url: 'https://api.github.com/users/hasancafarov/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/hasancafarov/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'fdemir',
    id: 48316033,
    node_id: 'MDQ6VXNlcjQ4MzE2MDMz',
    avatar_url: 'https://avatars.githubusercontent.com/u/48316033?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/fdemir',
    html_url: 'https://github.com/fdemir',
    followers_url: 'https://api.github.com/users/fdemir/followers',
    following_url: 'https://api.github.com/users/fdemir/following{/other_user}',
    gists_url: 'https://api.github.com/users/fdemir/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/fdemir/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/fdemir/subscriptions',
    organizations_url: 'https://api.github.com/users/fdemir/orgs',
    repos_url: 'https://api.github.com/users/fdemir/repos',
    events_url: 'https://api.github.com/users/fdemir/events{/privacy}',
    received_events_url: 'https://api.github.com/users/fdemir/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'KadirHaktan',
    id: 38834423,
    node_id: 'MDQ6VXNlcjM4ODM0NDIz',
    avatar_url: 'https://avatars.githubusercontent.com/u/38834423?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/KadirHaktan',
    html_url: 'https://github.com/KadirHaktan',
    followers_url: 'https://api.github.com/users/KadirHaktan/followers',
    following_url:
      'https://api.github.com/users/KadirHaktan/following{/other_user}',
    gists_url: 'https://api.github.com/users/KadirHaktan/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/KadirHaktan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/KadirHaktan/subscriptions',
    organizations_url: 'https://api.github.com/users/KadirHaktan/orgs',
    repos_url: 'https://api.github.com/users/KadirHaktan/repos',
    events_url: 'https://api.github.com/users/KadirHaktan/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/KadirHaktan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'haydar',
    id: 6452942,
    node_id: 'MDQ6VXNlcjY0NTI5NDI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6452942?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/haydar',
    html_url: 'https://github.com/haydar',
    followers_url: 'https://api.github.com/users/haydar/followers',
    following_url: 'https://api.github.com/users/haydar/following{/other_user}',
    gists_url: 'https://api.github.com/users/haydar/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/haydar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/haydar/subscriptions',
    organizations_url: 'https://api.github.com/users/haydar/orgs',
    repos_url: 'https://api.github.com/users/haydar/repos',
    events_url: 'https://api.github.com/users/haydar/events{/privacy}',
    received_events_url: 'https://api.github.com/users/haydar/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'HakanUcaar',
    id: 11438373,
    node_id: 'MDQ6VXNlcjExNDM4Mzcz',
    avatar_url: 'https://avatars.githubusercontent.com/u/11438373?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/HakanUcaar',
    html_url: 'https://github.com/HakanUcaar',
    followers_url: 'https://api.github.com/users/HakanUcaar/followers',
    following_url:
      'https://api.github.com/users/HakanUcaar/following{/other_user}',
    gists_url: 'https://api.github.com/users/HakanUcaar/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/HakanUcaar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/HakanUcaar/subscriptions',
    organizations_url: 'https://api.github.com/users/HakanUcaar/orgs',
    repos_url: 'https://api.github.com/users/HakanUcaar/repos',
    events_url: 'https://api.github.com/users/HakanUcaar/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/HakanUcaar/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'saidahmetbayrak',
    id: 16213420,
    node_id: 'MDQ6VXNlcjE2MjEzNDIw',
    avatar_url: 'https://avatars.githubusercontent.com/u/16213420?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/saidahmetbayrak',
    html_url: 'https://github.com/saidahmetbayrak',
    followers_url: 'https://api.github.com/users/saidahmetbayrak/followers',
    following_url:
      'https://api.github.com/users/saidahmetbayrak/following{/other_user}',
    gists_url: 'https://api.github.com/users/saidahmetbayrak/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/saidahmetbayrak/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/saidahmetbayrak/subscriptions',
    organizations_url: 'https://api.github.com/users/saidahmetbayrak/orgs',
    repos_url: 'https://api.github.com/users/saidahmetbayrak/repos',
    events_url: 'https://api.github.com/users/saidahmetbayrak/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/saidahmetbayrak/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'farukx',
    id: 55917247,
    node_id: 'MDQ6VXNlcjU1OTE3MjQ3',
    avatar_url: 'https://avatars.githubusercontent.com/u/55917247?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/farukx',
    html_url: 'https://github.com/farukx',
    followers_url: 'https://api.github.com/users/farukx/followers',
    following_url: 'https://api.github.com/users/farukx/following{/other_user}',
    gists_url: 'https://api.github.com/users/farukx/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/farukx/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/farukx/subscriptions',
    organizations_url: 'https://api.github.com/users/farukx/orgs',
    repos_url: 'https://api.github.com/users/farukx/repos',
    events_url: 'https://api.github.com/users/farukx/events{/privacy}',
    received_events_url: 'https://api.github.com/users/farukx/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'tosunthex',
    id: 2063672,
    node_id: 'MDQ6VXNlcjIwNjM2NzI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2063672?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tosunthex',
    html_url: 'https://github.com/tosunthex',
    followers_url: 'https://api.github.com/users/tosunthex/followers',
    following_url:
      'https://api.github.com/users/tosunthex/following{/other_user}',
    gists_url: 'https://api.github.com/users/tosunthex/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/tosunthex/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tosunthex/subscriptions',
    organizations_url: 'https://api.github.com/users/tosunthex/orgs',
    repos_url: 'https://api.github.com/users/tosunthex/repos',
    events_url: 'https://api.github.com/users/tosunthex/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/tosunthex/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sertunc',
    id: 6024003,
    node_id: 'MDQ6VXNlcjYwMjQwMDM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6024003?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sertunc',
    html_url: 'https://github.com/sertunc',
    followers_url: 'https://api.github.com/users/sertunc/followers',
    following_url:
      'https://api.github.com/users/sertunc/following{/other_user}',
    gists_url: 'https://api.github.com/users/sertunc/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/sertunc/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sertunc/subscriptions',
    organizations_url: 'https://api.github.com/users/sertunc/orgs',
    repos_url: 'https://api.github.com/users/sertunc/repos',
    events_url: 'https://api.github.com/users/sertunc/events{/privacy}',
    received_events_url: 'https://api.github.com/users/sertunc/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Acidooo',
    id: 15827009,
    node_id: 'MDQ6VXNlcjE1ODI3MDA5',
    avatar_url: 'https://avatars.githubusercontent.com/u/15827009?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Acidooo',
    html_url: 'https://github.com/Acidooo',
    followers_url: 'https://api.github.com/users/Acidooo/followers',
    following_url:
      'https://api.github.com/users/Acidooo/following{/other_user}',
    gists_url: 'https://api.github.com/users/Acidooo/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Acidooo/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Acidooo/subscriptions',
    organizations_url: 'https://api.github.com/users/Acidooo/orgs',
    repos_url: 'https://api.github.com/users/Acidooo/repos',
    events_url: 'https://api.github.com/users/Acidooo/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Acidooo/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ozcanyarimdunya',
    id: 12237463,
    node_id: 'MDQ6VXNlcjEyMjM3NDYz',
    avatar_url: 'https://avatars.githubusercontent.com/u/12237463?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ozcanyarimdunya',
    html_url: 'https://github.com/ozcanyarimdunya',
    followers_url: 'https://api.github.com/users/ozcanyarimdunya/followers',
    following_url:
      'https://api.github.com/users/ozcanyarimdunya/following{/other_user}',
    gists_url: 'https://api.github.com/users/ozcanyarimdunya/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ozcanyarimdunya/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/ozcanyarimdunya/subscriptions',
    organizations_url: 'https://api.github.com/users/ozcanyarimdunya/orgs',
    repos_url: 'https://api.github.com/users/ozcanyarimdunya/repos',
    events_url: 'https://api.github.com/users/ozcanyarimdunya/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ozcanyarimdunya/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Mehmet-Erdem-Akin',
    id: 52917167,
    node_id: 'MDQ6VXNlcjUyOTE3MTY3',
    avatar_url: 'https://avatars.githubusercontent.com/u/52917167?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Mehmet-Erdem-Akin',
    html_url: 'https://github.com/Mehmet-Erdem-Akin',
    followers_url: 'https://api.github.com/users/Mehmet-Erdem-Akin/followers',
    following_url:
      'https://api.github.com/users/Mehmet-Erdem-Akin/following{/other_user}',
    gists_url: 'https://api.github.com/users/Mehmet-Erdem-Akin/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Mehmet-Erdem-Akin/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/Mehmet-Erdem-Akin/subscriptions',
    organizations_url: 'https://api.github.com/users/Mehmet-Erdem-Akin/orgs',
    repos_url: 'https://api.github.com/users/Mehmet-Erdem-Akin/repos',
    events_url:
      'https://api.github.com/users/Mehmet-Erdem-Akin/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Mehmet-Erdem-Akin/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'gusanmaz',
    id: 2552975,
    node_id: 'MDQ6VXNlcjI1NTI5NzU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2552975?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gusanmaz',
    html_url: 'https://github.com/gusanmaz',
    followers_url: 'https://api.github.com/users/gusanmaz/followers',
    following_url:
      'https://api.github.com/users/gusanmaz/following{/other_user}',
    gists_url: 'https://api.github.com/users/gusanmaz/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gusanmaz/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gusanmaz/subscriptions',
    organizations_url: 'https://api.github.com/users/gusanmaz/orgs',
    repos_url: 'https://api.github.com/users/gusanmaz/repos',
    events_url: 'https://api.github.com/users/gusanmaz/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/gusanmaz/received_events',
    type: 'User',
    site_admin: false,
  },
];
