export default {
  login: 'NisanurBulut',
  id: 9026717,
  node_id: 'MDQ6VXNlcjkwMjY3MTc=',
  avatar_url: 'https://avatars.githubusercontent.com/u/9026717?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/NisanurBulut',
  html_url: 'https://github.com/NisanurBulut',
  followers_url: 'https://api.github.com/users/NisanurBulut/followers',
  following_url:
    'https://api.github.com/users/NisanurBulut/following{/other_user}',
  gists_url: 'https://api.github.com/users/NisanurBulut/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/NisanurBulut/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/NisanurBulut/subscriptions',
  organizations_url: 'https://api.github.com/users/NisanurBulut/orgs',
  repos_url: 'https://api.github.com/users/NisanurBulut/repos',
  events_url: 'https://api.github.com/users/NisanurBulut/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/NisanurBulut/received_events',
  type: 'User',
  site_admin: false,
  name: 'NisanurBulut',
  company: null,
  blog: 'https://stackoverflow.com/users/6830001/nisanur',
  location: 'Turkey/Eskişehir',
  email: null,
  hireable: null,
  bio:
    'Computer Engineer\r\n\r\ntalk is cheap show me the code ~Linus Torvalds',
  twitter_username: null,
  public_repos: 36,
  public_gists: 0,
  followers: 62,
  following: 17,
  created_at: '2014-10-05T15:12:44Z',
  updated_at: '2021-02-19T17:04:59Z',
};
