//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CihazDetay
    {
        public int DetayId { get; set; }
        public Nullable<int> DetayCihazId { get; set; }
        public string DetayStr { get; set; }
        public Nullable<System.DateTime> DetayErisimSonTar { get; set; }
        public string CSurum { get; set; }
        public string DSurum { get; set; }
        public string YSurum { get; set; }
    }
}
