//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CihazDurum
    {
        public int Did { get; set; }
        public string Durum { get; set; }
    }
}
