//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiTokenAuthentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int UId { get; set; }
        public string UAd { get; set; }
        public string UPass { get; set; }
        public Nullable<int> PID { get; set; }
    }
}
